spring:
  application:
    name: maps
  datasource:
    url: jdbc:postgresql://localhost:5432/maps
    username: username1
    password: password1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect